name: Test all
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Npm install
      run: npm install
    
    - name: Mocha
      run: node ./node_module/mocha/bin/mocha -u bdd -r ts-node/register --timeout 999999 --colors ./tests/**/*.test.ts
